version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
build_script:
- ps: >-
    .\buildInstaller.ps1

    Get-ChildItem .\setup\Output\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    Get-ChildItem .\release\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    Get-ChildItem .\release\*.jar | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
